# Generated by Django 4.2.8 on 2023-12-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('task', models.TextField(blank=True, verbose_name='Задача')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания задачи')),
                ('datecompleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения задачи')),
                ('important', models.BooleanField(default=False, verbose_name='ВАЖНАЯ ЗАДАЧА')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
